name: Docker Tag Notifier

on:
  schedule:
    # Run the workflow every hour (adjust as needed)
    - cron: '0 * * * *'

  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main

jobs:
  check_docker_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Docker Tag Check Script
        env:
          PUSHBULLET_ACCESS_TOKEN: ${{ secrets.PUSHBULLET_ACCESS_TOKEN }}
          PUSHBULLET_CHANNEL_TAG: ${{ secrets.PUSHBULLET_CHANNEL_TAG }}
        run: |
          python main.py
