name: Docker Tag Tracker

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  check_docker_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download the data artifact
      uses: actions/download-artifact@v3
      with:
        name: last_docker_tag

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Docker Tag Tracker
      env:
        PUSHBULLET_ACCESS_TOKEN: ${{ secrets.PUSHBULLET_ACCESS_TOKEN }}
        PUSHBULLET_CHANNEL_TAG: ${{ secrets.PUSHBULLET_CHANNEL_TAG }}
      run: |
        python main.py
  
    - name: Upload the generated data as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: last_docker_tag
        path: last_docker_tag.txt
